### ISSUE TITLE
txt locatuii

### ISSUE THREAD

**Issue by rafstahelin** [darkpixel/darkprompts#1]

**Comment by rafstahelin** [comment]
where do i place the txt file. i see in your screenshot it is \input/prompts/
<img width="352" alt="image" src="https://github.com/darkpixel/darkprompts/assets/64715158/94812689-64f1-4b8b-868d-5f9df3bd4145">

**Comment by rafstahelin** [comment]
just copied file path

**Comment by darkpixel** [comment]
The paths are relative to the ComfyUI folder, so in my example a relative path like ```inputs/hair_color.txt``` would translate into ```<comfyui folder>/inputs/hair_color.txt``` or in my very specific case ```/home/aaron/code/ComfyUI/inputs/hair_color.txt```.

Or, like you discovered, you can just put in a full path.
