### ISSUE TITLE
need to pump lora trigger word 2x to get it to appear

### ISSUE THREAD

**Issue by rafstahelin** [darkpixel/darkprompts#2]
[workflow (14).json](https://github.com/darkpixel/darkprompts/files/13998650/workflow.14.json)

is there a reason it does this?

<img width="431" alt="image" src="https://github.com/darkpixel/darkprompts/assets/64715158/331e60df-dd4b-4d32-92d3-f11e195b1d5d">

**Comment by darkpixel** [comment]
It's working fine with my LORAs.  The string that leaves my final prompt box goes into a "LORA Tag Loader" node.

Can you go into a bit more detail on what you're running into?

**Comment by rafstahelin** [comment]
The Lora weight doesn’t get picked up til strength (lorariggername:2) in the prompt Usually just at default it appears It’s strange I haven’t tried with other Lora’sBest, Raf On 20 Jan 2024, at 17:57, Aaron C. de Bruyn ***@***.***> wrote:﻿
It's working fine with my LORAs.  The string that leaves my final prompt box goes into a "LORA Tag Loader" node.
Can you go into a bit more detail on what you're running into?

**Comment by darkpixel** [comment]
I just noticed you attached your workflow.  Thanks for that.

DarkPrompt doesn't load LORAs...does your text file contain LORA loading instructions?  i.e. ```<lora:somelora:0.8>```
If so, you need to run the output through a LORA loading node like https://github.com/badjeff/comfyui_lora_tag_loader

Example circled in red:

![Screenshot from 2024-01-20 10-19-59](https://github.com/darkpixel/darkprompts/assets/158380/75361de0-72d6-4e6f-9329-adfe2dcae9b1)

One other explanation might be the "text" box on the DarkPrompt node being confusing.

The DarkPrompt node has two inputs--one for a filename and one for text.  BOTH of those get loaded if they are provided and then *ONE* random line is chosen from all the lines loaded.

So if you had a file that contained:
```
a woman
```
...and in the text box you entered:
```
a man
```

DarkPrompt would be randomly choosing between ```a woman``` and ```a man```.

If you want to include some text that is always included, you could enter it in the prefix or suffix box.

In this example, the a-woman.txt file contains one line that says ```a woman```.  The text input box contains ```a man```, and the prefix box contains ```some-lora-trigger-word-always-included```:

![Screenshot from 2024-01-20 10-28-13](https://github.com/darkpixel/darkprompts/assets/158380/dc204306-a917-46a5-9196-7e4d8b4f977c)

DarkPrompt will pick ONE line randomly from the combined file and text inputs, add the prefix and suffix, and output the string.

**Comment by darkpixel** [comment]
Also, the RGThree add-on has a "Debug Any" node that's helpful to see your prompt right before you feed it into your Prompt Encoder.

**Comment by rafstahelin** [comment]
Ah ok that's very useful thanks for pointing it out

**Comment by darkpixel** [comment]
My pleasure!  I hope you enjoy it.

I released an update about an hour ago that lets you chain prompts together.
