### ISSUE TITLE
from where did you got the source node which is shown in the image?

### ISSUE THREAD

**Issue by utkd135** [darkpixel/darkprompts#7]
there is a source node in the image, I am unable to find it, can you help me find that ?

**Comment by darkpixel** [comment]
Which source node are you talking about?  The DarkPrompt node?

One thing you can try is downloading that image from GitHub and importing it into ComfyUI.  It has embedded information that will re-create the workflow you see in the image.

**Comment by darkpixel** [comment]
Hey @utkd135.  Are you still having trouble finding it?

**Comment by utkd135** [comment]
sorry buddy couldn't follow up, I forgot what was the exact issue, but I was able to build a node for my project. Thank you.

**Comment by darkpixel** [comment]
That's great.  Don't hesitate to reach out if you have any more trouble!
